In [ ]:
#Transformez vos données en tableaux
# Créez un tableau avec NumPy
import numpy as np
## créer un matrice de 2 colones et 3 lignes
table1=np.array([[1,2],[3,4],[5,6]])
## créer un matrice de 3 colones et 2 lignes
table2=np.array([[1,2,3],[4,5,6]])
## tableau de 3*5 rempli de 1
table3=np.ones((3,5))
# un tableau de 3x5 rempli de valeurs aléatoires entières, comprises entre 1 et 10
table4=np.random.randint(1, 10, size=(3, 5))

In [5]:
#L’analogie entre les arrays et les matrices
import numpy as np
matrice1=np.array([[1,2],[3,4]])
matrice2=np.array([[5,10],[15,20]])
# addition
matrice3=matrice1+matrice2
print(matrice3)
# soustraction
matrice4=matrice1-matrice2
print(matrice4)
# multiplication
matrice5=matrice1*matrice2
print(matrice5)
# division
matrice6=matrice1/matrice2
print(matrice6)

[[ 6 12]
 [18 24]]
[[ -4  -8]
 [-12 -16]]
[[ 5 20]
 [45 80]]
[[0.2 0.2]
 [0.2 0.2]]


In [12]:
#Maîtrisez les manipulations avancées d’array
import numpy as np
#revenu,mensualité,age
hugo=[1300,400,23]
richard=[1700,560,24]
emilie=[2500,900,30]
gaspard=[3000,1000,22]
yohann=[2400,700,28]
chloe=[3000,700,34]
mathieu=[3500,900,35]
luc=[4000,1200,35]
rachel=[3300,950,27]
maude=[1850,600,25]

tableau = [hugo,richard,emilie,gaspard,yohann,chloe,mathieu,luc,rachel,maude]

data = np.array(tableau)

# accéder à un element spécifiques (premiere ligne,premiere colone)
data[0,0]
# accéder à une ligne spécifique (premiere ligne)
data[0,:]
# accéder à une colone spécifique (troisiéme colone)
data[:,2]
# accéder au données sous condition (affiche les données quand les valeurs de troisieme colone sont égales ou moins de 25)
data[data[:,2]<=25]
# ajouter une nouvelle ligne
fred=[1750,650,21]
np.vstack((data,fred))

array([[1300,  400,   23],
       [1700,  560,   24],
       [2500,  900,   30],
       [3000, 1000,   22],
       [2400,  700,   28],
       [3000,  700,   34],
       [3500,  900,   35],
       [4000, 1200,   35],
       [3300,  950,   27],
       [1850,  600,   25],
       [1750,  650,   21]])

In [30]:
#Exercice
#https://openclassrooms.com/fr/courses/7771531-decouvrez-les-librairies-python-pour-la-data-science/7857032-transformez-vos-donnees-en-tableaux
import numpy as np

hugo = [1800, 21, 0]
richard = [1500, 54, 2]
emilie = [2200, 28, 3]
pierre = [3000, 37, 1]
paul = [2172, 37, 2]
deborah = [5000, 32, 0]
yohann = [1400, 23, 0]
anne = [1200, 25, 1]
thibault = [1100, 19, 0]
emmanuel = [1300, 31, 2]

tableau = [hugo, richard, emilie, pierre, paul, deborah,yohann, anne, thibault, emmanuel]

data = np.array(tableau)

print("Informations de Paul :")
print(data[4, :])
print("-")
print("Ses mensualités maximales sont de :", round(data[4,0]*0.35, 2), "€")
print("-")

louise=[1900,31,1]
np.vstack((data,louise))

revenus = data[:, 0]
print(revenus)

Informations de Paul :
[2172   37    2]
-
Ses mensualités maximales sont de : 760.2 €
-
[1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]
