In [1]:
#Différencier les arrays des listes classiques
import numpy as np
## les arrays NumPy
revenus = [1800, 1500, 2200, 3000, 2172]
### calculer la moyenne
np.mean(revenus)
### quelques d'autres fonction de numpy
#### la valeur absolue abs(x)
#### l'exponentielle exp(x)
#### le logarithme log(x)

2134.4

In [3]:
#Créer un array(tableau) numpy
import numpy as np
revenus = [1800, 1500, 2200, 3000, 2172]
revenus_array = np.array(revenus)

## autres fonctions numpy permettent de créer des arrays
### np.zeros(n): permet de créer un array rempli de 0, de n éléments ;
### np.ones(n) : similaire en tous points à la fonction présentée ci-dessus, à la différence que l’array sera rempli cette fois-ci de 1 ;
### np.arange(i, j, p)  : permet de créer un array rempli avec une séquence linéaire, qui ira de  i  à  j, par pas de  p  ;
### np.linspace(i, j, n) : permet de créer un array de  n  valeurs espacées uniformément entre  i  et  j

In [4]:
#Créer un array monotype
import numpy as np
revenus = [1800, 1500, 2200, 3000, 2172]
revenus_array = np.array(revenus)
revenus_array.dtype

dtype('int64')

In [13]:
#Sélectionner des éléements au sein d'un array
import numpy as np
revenus = [1800, 1500, 2200, 3000, 2172]
revenus_array = np.array(revenus)

## accéder à un seul élément
### accéder au 5éme élement
revenus_array[4]
### accéder au dérnier élement
revenus_array[-1]
### modifier un élement
revenus_array[1]=1900
print(revenus_array)


## accéder à plusieurs éléments
### nom_array[i:j:p]
#### i  : l’indice du début ;
#### j  : l’indice de fin ;
#### p : le pas.
revenus_array[0:3] += 100
print(revenus_array)

## accéder à plusieurs éléments selon une condition
### nom_array[condition de sélection]
revenus_array[(revenus_array>2000)&(revenus_array<3000)]

[1800 1900 2200 3000 2172]
[1900 2000 2300 3000 2172]


array([2300, 2172])

In [36]:
#Utilisez les méthodes d'array
import numpy as np
revenus = [1800, 1500, 2200, 3000, 2172]
revenus_array = np.array(revenus)

## savoir le nombre des elements dans notre array
revenus_array.shape

## calculer le maximum et le minimum
revenus_array.max()
revenus_array.min()

## accéder à l’indice de l’élement minimum ou maximum :
revenus_array.argmin()
revenus_array.argmax()

## odonner par ordre croissant:
revenus_array.sort()

## calculer la somme :
revenus_array.sum()

10672

In [38]:
#Exercice
#https://openclassrooms.com/fr/courses/7771531-decouvrez-les-librairies-python-pour-la-data-science/7856832-creez-vos-premiers-arrays-avec-numpy

import numpy as np

liste = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]

revenus = np.array(liste)
print(revenus)

haut_revenus = revenus[(liste_array>=3000)]
print("Les clients qui ont haute revenus",haut_revenus)

somme = revenus.sum()*12
print("La somme de 12 mois est égale à",somme)

moyenne = np.mean(revenus)
print("Moyenne de revenues est égale à",moyenne)

revenus[revenus == 1400] = 1600
print("Revenues apres promotion : ",revenus)

[1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]
Les clients qui ont haute revenus [3000 5000]
La somme de 12 mois est égale à 248064
Moyenne de revenues est égale à 2067.2
Revenues apres promotion :  [1800 1500 2200 3000 2172 5000 1600 1200 1100 1300]
